name: Label & comment issues

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened

jobs:
  label_and_comment_issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Attach labels to new or reopened issues
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      - name: Comment on new or reopened issue
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

      - name: Comment when issue is closed
        if: github.event.action == 'closed'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue is now resolved.

  congratulate_first_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if this is user's first PR
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            const user = context.payload.pull_request.user.login;
            const firstPR = pulls.filter(pr => pr.user.login === user).length === 1;
            return firstPR;
      - name: Congratulate first-time PR user
        if: steps.check.outputs.result == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎉 Congratulations on opening your first pull request! We appreciate your contribution!
